# Generated by Django 6.0.1 on 2026-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, unique=True)),
                ('coach_name', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=55, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
