# Generated by Django 6.0.1 on 2026-02-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('scores', '0002_remove_score_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_score', to='scores.score'),
        ),
    ]
