# Generated by Django 6.0.1 on 2026-02-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='match',
        ),
    ]
